from aiogram.dispatcher.filters.state import StatesGroup, State


class UsersTest_1(StatesGroup):
    name = State()
    cafe = State()
    one_one = State()
    one_two = State()
    one_three = State()
    two_one = State()
    two_two = State()
    two_three = State()
    three_one = State()
    three_two = State()
    three_three = State()
    three_four = State()
    three_five = State()
    three_six = State()
    three_seven = State()
    four_one = State()
    four_two = State()
    four_three = State()
    five_one = State()
    five_two = State()
    five_three = State()
    attestation_one = State()
    attestation_two = State()
    attestation_three = State()
    attestation_four = State()
