from aiogram.dispatcher.filters.state import StatesGroup, State


class UsersTest_1(StatesGroup):
    name = State()
    cafe = State()
    next_cmd = State()
    next_cmd_2 = State()
    one_1 = State()
    one_2 = State()
    one_3 = State()
    one_4 = State()
    one_5 = State()
    one_6 = State()
    one_7 = State()
    two_1 = State()
    two_2 = State()
    two_3 = State()
    two_4 = State()
    two_5 = State()
    two_6 = State()
    two_7 = State()
    attestation_1 = State()
    attestation_2 = State()
    attestation_3 = State()
    attestation_4 = State()
    attestation_5 = State()
    attestation_6 = State()
    attestation_7 = State()
    attestation_8 = State()
    attestation_9 = State()
    attestation_10 = State()
    attestation_11 = State()
    attestation_12 = State()
    attestation_13 = State()
    attestation_14 = State()
    attestation_15 = State()
    attestation_16 = State()
    attestation_17 = State()
    attestation_18 = State()
    attestation_19 = State()
